customhost = "employee.cuxnebfeu6fk.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "Bait3273"
customdb = "employee"
customdb = "Employee"
custombucket = "leejunjie-bucket"
customregion = "us-east-1"